spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/2022212808?createDatabaseIfNotExist=true'
    username: 2022212808
    password: 2022212808
  data:
    redis:
      host: 120.46.159.231
      port: 6379
      username: default
      password: 2046
      database: 9
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
my:
  key: abc
server:
  port: 8080